spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
    url: jdbc:mysql://106.54.134.159:3306/account?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null #设置全局返回值为null时，不返回该字段，但是若代码中有使用@EnableWebMvc后失效

server:
  port: 3005
#  servlet:
#    context-path: /sell
